spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/fornecedor?useTimezone=true
    username: root    
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
